"""create initial greencloud tables

Revision ID: 7d4f5a2fc44c
Revises: 
Create Date: 2026-09-18 20:37:00.657384
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '7d4f5a2fc44c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('AWS', 'AZURE', 'GCP', 'PRIVATE', name='cloudprovidertype'), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=150), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('memory_gb', sa.Float(), nullable=False),
    sa.Column('storage_gb', sa.Float(), nullable=False),
    sa.Column('cpu_power_efficiency', sa.Float(), nullable=False),
    sa.Column('dcie', sa.Float(), nullable=False),
    sa.Column('cost_per_cpu_hour', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workload_type', sa.Enum('BATCH', 'REAL_TIME', 'MACHINE_LEARNING', 'HPC', name='workloadtype'), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('memory_gb', sa.Float(), nullable=False),
    sa.Column('storage_gb', sa.Float(), nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=False),
    sa.Column('deadline_minutes', sa.Integer(), nullable=False),
    sa.Column('data_transfer_gb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('carbon_intensity', sa.Float(), nullable=False),
    sa.Column('measurement_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['cloud_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workload_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('energy_consumption_kwh', sa.Float(), nullable=False),
    sa.Column('carbon_emissions_kg', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('execution_time_minutes', sa.Float(), nullable=False),
    sa.Column('carbon_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['cloud_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workload_id'], ['workloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_results')
    op.drop_table('carbon_data')
    op.drop_table('workloads')
    op.drop_table('documents')
    op.drop_table('cloud_providers')
    # ### end Alembic commands ###