"""add execution time factor

Revision ID: afe68a0d5287
Revises: 7d4f5a2fc44c
Create Date: 2026-09-19 08:22:47.447321
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'afe68a0d5287'
down_revision: Union[str, Sequence[str], None] = '7d4f5a2fc44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_providers', sa.Column('execution_time_factor', sa.Float(), nullable=False, server_default="1.0",),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_providers', 'execution_time_factor')
    # ### end Alembic commands ###