import json
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.agents.tools import (
    AGENT_TOOLS,
    run_optimization_tool,
)
from app.rag.retriever import RAGRetriever
from app.services.llm_service import LLMService


class GreenCloudAgent:
    """
    Agentic orchestration layer for GreenCloud Optimizer.

    The LLM decides which available tool should be used.
    Deterministic application services perform the actual
    calculations and retrieval.
    """

    def __init__(self, db: AsyncSession):
        self.db = db
        self.llm_service = LLMService()
        self.retriever = RAGRetriever()

    async def answer(self, query, workload_id=None):
        if not query.strip():
            raise ValueError("Query cannot be empty")

        # ---------------------------------------------------------
        # 1. Determine whether this is an optimization request
        # ---------------------------------------------------------

        optimization_request = (
            workload_id is not None
            and any(
                keyword in query.lower()
                for keyword in [
                    "optimize",
                    "optimization",
                    "provider",
                    "carbon-efficient",
                    "carbon efficient",
                    "schedule",
                    "scheduling",
                ]
            )
        )

        # ---------------------------------------------------------
        # 2. Optimization path
        #
        # The application already knows the workload ID.
        # Therefore, we explicitly invoke the deterministic
        # optimization tool rather than allowing the LLM to
        # invent or modify the workload identifier.
        # ---------------------------------------------------------

        if optimization_request:
            result = await run_optimization_tool(
                db=self.db,
                workload_id=UUID(str(workload_id)),
                algorithm="cegp",
            )

            result_text = json.dumps(result, indent=2)

            system_prompt = """You are the GreenCloud Optimizer AI assistant.

    Explain the optimization result provided by the deterministic
    GreenCloud optimization engine.

    Important rules:
    - Do not modify any numerical values.
    - Do not invent numerical values.
    - Do not perform your own calculations.
    - Clearly state the selected provider and region.
    - Explain that the result was produced by the deterministic
    GreenCloud optimization engine.
    - Do not call or request another tool.
    - Keep the explanation concise and technically accurate.
    """

            user_prompt = f"""User request:

    {query}

    Deterministic optimization result:

    {result_text}

    Explain this result to the user."""
            
            return await self.llm_service.generate(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
            )

        # ---------------------------------------------------------
        # 3. General knowledge / RAG path
        # ---------------------------------------------------------

        system_prompt = """You are the GreenCloud Optimizer AI assistant.

    Answer the user's question using the GreenCloud research
    knowledge base.

    Important rules:
    - Use research context when available.
    - Do not invent facts.
    - Do not perform carbon, energy, cost, or optimization
    calculations yourself.
    - Clearly distinguish research-paper results from results
    generated by the GreenCloud prototype.
    - Keep the answer technically accurate.
    """

        user_message = query

        messages = [
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": user_message,
            },
        ]

        # ---------------------------------------------------------
        # 4. Let the LLM decide whether RAG is required
        # ---------------------------------------------------------

        response = await self.llm_service.client.chat.completions.create(
            model=self.llm_service.model,
            messages=messages,
            tools=AGENT_TOOLS,
            tool_choice="auto",
            max_completion_tokens=1024,
        )

        assistant_message = response.choices[0].message

        # ---------------------------------------------------------
        # 5. If no tool is requested, return the answer directly
        # ---------------------------------------------------------

        if not assistant_message.tool_calls:
            if not assistant_message.content:
                raise ValueError(
                    "LLM returned an empty response"
                )

            return assistant_message.content

        # ---------------------------------------------------------
        # 6. Execute requested tools
        # ---------------------------------------------------------

        messages.append(
            {
                "role": "assistant",
                "content": assistant_message.content,
                "tool_calls": [
                    {
                        "id": tool_call.id,
                        "type": "function",
                        "function": {
                            "name": tool_call.function.name,
                            "arguments": tool_call.function.arguments,
                        },
                    }
                    for tool_call in assistant_message.tool_calls
                ],
            }
        )

        for tool_call in assistant_message.tool_calls:
            tool_name = tool_call.function.name

            try:
                arguments = json.loads(
                    tool_call.function.arguments
                )
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"Invalid tool arguments: {tool_call.function.arguments}"
                ) from exc

            if tool_name == "search_greencloud_knowledge":
                tool_query = arguments.get("query")

                if not tool_query:
                    raise ValueError(
                        "RAG tool requires a query."
                    )

                documents = await self.retriever.retrieve(
                    query=tool_query,
                    limit=5,
                )

                tool_result = "\n\n---\n\n".join(
                    (
                        f"Source: {document.source_name}\n"
                        f"Chunk: {document.chunk_index}\n"
                        f"{document.content}"
                    )
                    for document in documents
                )

                if not tool_result:
                    tool_result = (
                        "No relevant documents were found."
                    )

            else:
                tool_result = (
                    f"Unsupported tool requested: {tool_name}"
                )

            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "content": tool_result,
                }
            )

        # ---------------------------------------------------------
        # 7. Generate the final RAG-grounded answer
        # ---------------------------------------------------------

        final_response = await self.llm_service.client.chat.completions.create(
            model=self.llm_service.model,
            messages=messages,
            max_completion_tokens=1024,
        )

        content = final_response.choices[0].message.content

        if not content:
            raise ValueError(
                "LLM returned an empty final response"
            )

        return content