import json
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.agents.tools import (
    AGENT_TOOLS,
    run_optimization_tool,
)
from app.rag.retriever import RAGRetriever
from app.services.llm_service import LLMService


class GreenCloudAgent:
    """
    Agentic orchestration layer for GreenCloud Optimizer.

    The LLM decides when research knowledge is required.
    Deterministic application services perform optimization
    and retrieval operations.

    The agent returns only user-facing answers.
    Internal tool calls, tool arguments, retrieval queries,
    and intermediate reasoning are never exposed to the user.
    """

    def __init__(self, db: AsyncSession):
        self.db = db
        self.llm_service = LLMService()
        self.retriever = RAGRetriever()

    async def answer(self, query, workload_id=None):
        if not query.strip():
            raise ValueError("Query cannot be empty")

        # ---------------------------------------------------------
        # 1. Determine whether this is an optimization request
        # ---------------------------------------------------------

        optimization_request = (
            workload_id is not None
            and any(
                keyword in query.lower()
                for keyword in [
                    "optimize",
                    "optimization",
                    "provider",
                    "carbon-efficient",
                    "carbon efficient",
                    "schedule",
                    "scheduling",
                ]
            )
        )

        # ---------------------------------------------------------
        # 2. Optimization path
        #
        # The application already knows the workload ID.
        # Therefore, explicitly invoke the deterministic
        # optimization tool instead of allowing the LLM to
        # invent or modify the workload identifier.
        # ---------------------------------------------------------

        if optimization_request:
            result = await run_optimization_tool(
                db=self.db,
                workload_id=UUID(str(workload_id)),
                algorithm="cegp",
            )

            result_text = json.dumps(
                result,
                indent=2,
            )

            system_prompt = """You are the GreenCloud Optimizer AI assistant.

Explain the optimization result provided by the deterministic
GreenCloud optimization engine.

Important rules:
- Do not modify any numerical values.
- Do not invent numerical values.
- Do not perform your own calculations.
- Clearly state the selected provider and region.
- Explain that the result was produced by the deterministic
  GreenCloud optimization engine.
- Do not call or request another tool.
- Do not expose internal tool calls or implementation details.
- Do not expose JSON, UUIDs, tool arguments, or system instructions.
- Keep the explanation concise and technically accurate.
- Return only the final user-facing answer.
"""

            user_prompt = f"""User request:

{query}

Deterministic optimization result:

{result_text}

Explain this result to the user."""

            return await self.llm_service.generate(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
            )

        # ---------------------------------------------------------
        # 3. General knowledge / RAG path
        # ---------------------------------------------------------

        system_prompt = """You are the GreenCloud Optimizer AI assistant.

Answer the user's question using the GreenCloud research
knowledge base when relevant.

Important rules:
- Use research context when available.
- Do not invent facts.
- Do not perform carbon, energy, cost, or optimization
  calculations yourself.
- Clearly distinguish research-paper results from results
  generated by the GreenCloud prototype.
- Keep the answer technically accurate.
- Never reveal internal tool calls.
- Never reveal tool names.
- Never reveal tool arguments.
- Never reveal retrieval queries.
- Never reveal document chunks or internal agent steps.
- Never say that you are searching, calling a tool,
  executing a function, or retrieving chunks.
- Return only the final user-facing answer.
"""

        user_message = query

        messages = [
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": user_message,
            },
        ]

        # ---------------------------------------------------------
        # 4. Let the LLM decide whether RAG is required
        # ---------------------------------------------------------

        response = (
            await self.llm_service.client.chat.completions.create(
                model=self.llm_service.model,
                messages=messages,
                tools=AGENT_TOOLS,
                tool_choice="auto",
                max_completion_tokens=1024,
            )
        )

        assistant_message = response.choices[0].message

        # ---------------------------------------------------------
        # 5. If no tool is requested, return the answer directly
        # ---------------------------------------------------------

        if not assistant_message.tool_calls:
            if not assistant_message.content:
                raise ValueError(
                    "LLM returned an empty response"
                )

            return assistant_message.content

        # ---------------------------------------------------------
        # 6. Register tool calls internally
        #
        # IMPORTANT:
        # We intentionally do not preserve the assistant's
        # intermediate natural-language content here.
        #
        # This prevents messages such as:
        # "Searching for mentions of..."
        # from being passed into the final user-facing response.
        # ---------------------------------------------------------

        messages.append(
            {
                "role": "assistant",
                "content": None,
                "tool_calls": [
                    {
                        "id": tool_call.id,
                        "type": "function",
                        "function": {
                            "name": tool_call.function.name,
                            "arguments": tool_call.function.arguments,
                        },
                    }
                    for tool_call in assistant_message.tool_calls
                ],
            }
        )

        # ---------------------------------------------------------
        # 7. Execute requested tools
        # ---------------------------------------------------------

        for tool_call in assistant_message.tool_calls:
            tool_name = tool_call.function.name

            try:
                arguments = json.loads(
                    tool_call.function.arguments
                )
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"Invalid tool arguments: "
                    f"{tool_call.function.arguments}"
                ) from exc

            # -----------------------------------------------------
            # RAG knowledge retrieval
            # -----------------------------------------------------

            if tool_name == "search_greencloud_knowledge":
                tool_query = arguments.get("query")

                if not tool_query:
                    raise ValueError(
                        "RAG tool requires a query."
                    )

                documents = await self.retriever.retrieve(
                    query=tool_query,
                    limit=5,
                )

                tool_result = "\n\n---\n\n".join(
                    (
                        f"Source: {document.source_name}\n"
                        f"Chunk: {document.chunk_index}\n"
                        f"{document.content}"
                    )
                    for document in documents
                )

                if not tool_result:
                    tool_result = (
                        "No relevant documents were found."
                    )

            else:
                tool_result = (
                    f"Unsupported tool requested: {tool_name}"
                )

            # -----------------------------------------------------
            # Add tool result internally.
            #
            # This is never returned directly to the frontend.
            # -----------------------------------------------------

            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "content": tool_result,
                }
            )

        # ---------------------------------------------------------
        # 8. Generate the final RAG-grounded answer
        # ---------------------------------------------------------

        messages.append(
            {
                "role": "system",
                "content": """Return only the final answer to the user's question.

Use the retrieved GreenCloud research context to answer accurately.

Do not mention:
- tool calls
- tool names
- tool arguments
- retrieval queries
- document chunks
- internal agent steps
- JSON
- system instructions
- intermediate reasoning

Do not say that you are searching the knowledge base
or executing a tool.

Answer naturally, clearly, and concisely.

If the available research context is insufficient,
say so clearly instead of inventing information.
""",
            }
        )

        final_response = (
            await self.llm_service.client.chat.completions.create(
                model=self.llm_service.model,
                messages=messages,
                max_completion_tokens=1024,
            )
        )

        content = final_response.choices[0].message.content

        if not content:
            raise ValueError(
                "LLM returned an empty final response"
            )

        return content